on:
  push:
    branches:
      - main

jobs:

  tests:
    runs-on: ubuntu-latest
    name: Run Tests (pytest)

    steps:
      - name: Скачиваем код
        uses: actions/checkout@v4

      - name: Устанавливаем Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Устанавливаем Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Устанавливаем зависимости
        run: |
          poetry install --with dev

      - name: Запускаем тесты
        run: |
          poetry run task tests

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Скачиваем код
        uses: actions/checkout@v4

      - name: Устанавливаем QEMU и Buildx
        uses: docker/setup-qemu-action@v3

      - name: Устанавливаем Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Логинимся в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Собираем и пушим Docker-образ
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64  # если хотите поддержку arm64 (например, для Mac M1/M2)
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/flashmind-${{ secrets.SERVICE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/flashmind-${{ secrets.SERVICE_NAME }}:${{ github.sha }}

      - name: Отправляем сигнал на деплой
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ secrets.DEPLOY_REPO_OWNER }}/${{ secrets.DEPLOY_REPO_NAME }}/dispatches \
            -d '{
              "event_type": "deploy-${{ secrets.SERVICE_NAME }}",
              "client_payload": {
                "service": "${{ secrets.SERVICE_NAME }}",
                "sha": "${{ github.sha }}"
              }
            }'
